import { afterEach, describe, expect, it, vi } from 'vitest';

import {
  createStreamHub,
  ROUND_RULES,
  streamWithRetry,
} from '@/lib/orchestrator/stream-hub';
import type { SSEEvent } from '@/lib/types';
import type {
  CompletionRequest,
  CompletionResult,
  OpenRouterClient,
} from '@/lib/orchestrator/types';

afterEach(() => {
  vi.useRealTimers();
});

describe('stream-hub', () => {
  it('emits spec-shaped events with incrementing seq values', () => {
    const events: SSEEvent[] = [];
    const hub = createStreamHub((event) => {
      events.push(event);
    });

    hub.progress('d1', 1, 'independent');
    hub.chunk({
      discussionId: 'd1',
      logicalModelId: 'm1',
      actualModelId: 'm1',
      round: 1,
      text: 'hello',
    });
    hub.modelDone({
      discussionId: 'd1',
      logicalModelId: 'm1',
      actualModelId: 'm1',
      round: 1,
      inputTokens: 120,
      outputTokens: 48,
    });
    hub.modelError({
      discussionId: 'd1',
      logicalModelId: 'm2',
      actualModelId: null,
      round: 1,
      errorType: 'timeout',
      action: 'skipped',
      degradedTo: null,
      message: 'timed out',
    });
    hub.roundDone({
      discussionId: 'd1',
      round: 1,
      completedModels: ['m1'],
      skippedModels: ['m2'],
      failedModels: [
        {
          logical_model_id: 'm2',
          actual_model_id: null,
          error_type: 'timeout',
          action: 'skipped',
        },
      ],
      totalModels: 2,
    });
    hub.roundSummary('d1', 1, 2, {
      consensus: [
        {
          content: 'Round one is converging on a staged launch.',
          supporting_models: ['m1'],
          evidence_refs: ['round-1'],
        },
      ],
      disagreements: [],
      recommendation: 'Keep the rollout constrained for the next round.',
      confidence: 'medium',
      open_questions: ['What should the expansion gate be?'],
      evidence_refs: ['round-1'],
      disclaimer: 'Generated by secretary.',
      is_degraded: false,
    });
    hub.anonymize('d1', 2, ['Model A', 'Model B']);

    expect(events).toHaveLength(7);
    expect(
      events.map((event) => ('seq' in event.data ? event.data.seq : null))
    ).toEqual([1, 2, 3, 4, 5, 6, 7]);

    expect(events[0]).toEqual({
      type: 'progress',
      data: {
        round: 1,
        total_rounds: 3,
        phase: 'independent',
        seq: 1,
      },
    });

    expect(events[3]).toEqual({
      type: 'model_error',
      data: {
        logical_model_id: 'm2',
        actual_model_id: null,
        round: 1,
        error_type: 'timeout',
        action: 'skipped',
        degraded_to: null,
        message: 'timed out',
        seq: 4,
      },
    });

    expect(events[5]).toEqual({
      type: 'round_summary',
      data: {
        round: 1,
        next_round: 2,
        consensus: [
          {
            content: 'Round one is converging on a staged launch.',
            supporting_models: ['m1'],
            evidence_refs: ['round-1'],
          },
        ],
        disagreements: [],
        recommendation: 'Keep the rollout constrained for the next round.',
        confidence: 'medium',
        open_questions: ['What should the expansion gate be?'],
        evidence_refs: ['round-1'],
        disclaimer: 'Generated by secretary.',
        is_degraded: false,
        seq: 6,
      },
    });
  });

  it('maps billing and restore helpers into final SSE payloads', () => {
    const events: SSEEvent[] = [];
    const hub = createStreamHub((event) => {
      events.push(event);
    });

    hub.done('d1', { raw_cost: 0.08, platform_price: 0.1 });
    hub.restore('d1', 'completed', 3, 4);
    hub.error('d1', 'boom');
    hub.interruptAck('d1');

    expect(events).toEqual([
      {
        type: 'done',
        data: {
          total_raw_cost: 0.08,
          total_platform_price: 0.1,
          seq: 1,
        },
      },
      {
        type: 'restore',
        data: {
          resume_mode: 'state_restore',
          can_stream: false,
          current_status: 'completed',
          current_round: 3,
          last_completed_round: 4,
          completed_round_messages: [],
          summary: null,
        },
      },
      {
        type: 'error',
        data: {
          code: 'ORCHESTRATOR_ERROR',
          message: 'boom',
        },
      },
      {
        type: 'interrupt_ack',
        data: {
          status: 'acknowledged',
          message: 'Interrupt accepted for the next round.',
          seq: 2,
        },
      },
    ]);
  });

  it('retries once and then degrades to a fallback model', async () => {
    const events: SSEEvent[] = [];
    const hub = createStreamHub((event) => {
      events.push(event);
    });
    const attempts = new Map<string, number>();
    const client: OpenRouterClient = {
      async *streamCompletion(request: CompletionRequest) {
        const count = (attempts.get(request.model) ?? 0) + 1;
        attempts.set(request.model, count);

        if (request.model === 'google/gemini-3.1-pro') {
          throw new Error(`provider unavailable attempt ${count}`);
        }

        yield { text: 'fallback answer' };
        return {
          text: 'fallback answer',
          usage: { promptTokens: 100, completionTokens: 50 },
          finishReason: 'stop',
        } satisfies CompletionResult;
      },
      async complete() {
        throw new Error('not implemented');
      },
    };

    const result = await streamWithRetry({
      discussionId: 'd1',
      logicalModelId: 'google/gemini-3.1-pro',
      round: 1,
      prompt: 'Topic: test',
      client,
      hub,
      fallbackModelIds: ['google/gemini-3-flash'],
      pricingData: {
        'google/gemini-3-flash': {
          input: 0.5,
          output: 3,
        },
      },
    });

    expect(result.response).toMatchObject({
      modelId: 'google/gemini-3.1-pro',
      actualModelId: 'google/gemini-3-flash',
      inputTokens: 100,
      outputTokens: 50,
      rawCost: 0.0002,
    });
    expect(result.failures).toEqual([
      {
        logical_model_id: 'google/gemini-3.1-pro',
        actual_model_id: 'google/gemini-3.1-pro',
        error_type: 'server_error',
        action: 'retrying',
      },
      {
        logical_model_id: 'google/gemini-3.1-pro',
        actual_model_id: 'google/gemini-3-flash',
        error_type: 'server_error',
        action: 'degraded',
      },
    ]);

    const modelErrors = events.filter((event) => event.type === 'model_error');
    expect(modelErrors).toEqual([
      {
        type: 'model_error',
        data: {
          logical_model_id: 'google/gemini-3.1-pro',
          actual_model_id: 'google/gemini-3.1-pro',
          round: 1,
          error_type: 'server_error',
          action: 'retrying',
          degraded_to: null,
          message: 'Model request failed. Retrying google/gemini-3.1-pro.',
          seq: 1,
        },
      },
      {
        type: 'model_error',
        data: {
          logical_model_id: 'google/gemini-3.1-pro',
          actual_model_id: 'google/gemini-3-flash',
          round: 1,
          error_type: 'server_error',
          action: 'degraded',
          degraded_to: 'google/gemini-3-flash',
          message: 'Model request failed. Degraded google/gemini-3.1-pro to google/gemini-3-flash.',
          seq: 2,
        },
      },
    ]);

    expect(events.at(-1)).toEqual({
      type: 'model_done',
      data: {
        logical_model_id: 'google/gemini-3.1-pro',
        actual_model_id: 'google/gemini-3-flash',
        round: 1,
        tokens: {
          input: 100,
          output: 50,
        },
        seq: 4,
      },
    });
  });

  it('marks the model as skipped after TTFT timeout and exhausted retry budget', async () => {
    vi.useFakeTimers();

    const events: SSEEvent[] = [];
    const hub = createStreamHub((event) => {
      events.push(event);
    });
    const client: OpenRouterClient = {
      async *streamCompletion() {
        await new Promise((resolve) =>
          setTimeout(resolve, ROUND_RULES.MODEL_TTFT_TIMEOUT_MS + 1)
        );
        yield { text: 'late token' };
        return {
          text: 'late token',
          usage: { promptTokens: 1, completionTokens: 1 },
          finishReason: 'stop',
        } satisfies CompletionResult;
      },
      async complete() {
        throw new Error('not implemented');
      },
    };

    const run = streamWithRetry({
      discussionId: 'd1',
      logicalModelId: 'slow-model',
      round: 1,
      prompt: 'Topic: test',
      client,
      hub,
      fallbackModelIds: [],
    });

    await vi.advanceTimersByTimeAsync(ROUND_RULES.MODEL_TTFT_TIMEOUT_MS * 2 + 20);
    const result = await run;

    expect(result.response).toBeNull();
    expect(result.failures).toEqual([
      {
        logical_model_id: 'slow-model',
        actual_model_id: 'slow-model',
        error_type: 'timeout',
        action: 'retrying',
      },
      {
        logical_model_id: 'slow-model',
        actual_model_id: 'slow-model',
        error_type: 'timeout',
        action: 'skipped',
      },
    ]);

    expect(events.filter((event) => event.type === 'model_error')).toEqual([
      {
        type: 'model_error',
        data: {
          logical_model_id: 'slow-model',
          actual_model_id: 'slow-model',
          round: 1,
          error_type: 'timeout',
          action: 'retrying',
          degraded_to: null,
          message: 'Model timed out. Retrying slow-model.',
          seq: 1,
        },
      },
      {
        type: 'model_error',
        data: {
          logical_model_id: 'slow-model',
          actual_model_id: 'slow-model',
          round: 1,
          error_type: 'timeout',
          action: 'skipped',
          degraded_to: null,
          message: 'Model timed out. Skipping slow-model for this round.',
          seq: 2,
        },
      },
    ]);
  });
});
