/**
 * CLI-E01 — SSE 事件契约一致性验证
 *
 * 验证点：
 * 1. 所有 12 种事件类型可通过 sseEventSchema 运行时解析
 * 2. strict 模式：额外字段会被拒绝
 * 3. 字段名使用 snake_case（无 camelCase 漂移）
 * 4. required 字段缺失时解析失败
 */

import { describe, expect, it } from 'vitest';

import {
  sseEventSchema,
  progressEventSchema,
  chunkEventSchema,
  modelDoneEventSchema,
  modelErrorEventSchema,
  roundDoneEventSchema,
  anonymizeEventSchema,
  roundSummaryEventSchema,
  summaryEventSchema,
  doneEventSchema,
  restoreEventSchema,
  errorEventSchema,
  interruptAckEventSchema,
} from '@/lib/types/schemas';

// ─── Fixtures ─────────────────────────────────────────────────────────────────

const SUMMARY_FIXTURE = {
  consensus: [
    {
      content: 'Deploy with staged rollout.',
      supporting_models: ['m1', 'm2'],
      evidence_refs: ['r1'],
    },
  ],
  disagreements: [],
  recommendation: 'Proceed with staged rollout.',
  confidence: 'medium' as const,
  open_questions: [],
  evidence_refs: ['r1'],
  disclaimer: 'Generated by secretary.',
  is_degraded: false,
};

// ─── Individual schema tests ──────────────────────────────────────────────────

describe('CLI-E01 progress event', () => {
  it('parses valid progress event', () => {
    const event = {
      type: 'progress',
      data: { round: 1, total_rounds: 3, phase: 'independent', seq: 1 },
    };
    expect(() => progressEventSchema.parse(event)).not.toThrow();
  });

  it('rejects extra fields (strict)', () => {
    const event = {
      type: 'progress',
      data: { round: 1, total_rounds: 3, phase: 'independent', seq: 1, extra: 'field' },
    };
    expect(() => progressEventSchema.parse(event)).toThrow();
  });

  it('rejects missing seq', () => {
    const event = { type: 'progress', data: { round: 1, total_rounds: 3, phase: 'independent' } };
    expect(() => progressEventSchema.parse(event)).toThrow();
  });
});

describe('CLI-E01 chunk event', () => {
  it('parses valid chunk event', () => {
    const event = {
      type: 'chunk',
      data: {
        logical_model_id: 'openai/gpt-4',
        actual_model_id: 'openai/gpt-4',
        round: 1,
        content: 'hello',
        done: false,
        seq: 2,
      },
    };
    expect(() => chunkEventSchema.parse(event)).not.toThrow();
  });

  it('requires snake_case field names (not camelCase)', () => {
    // camelCase should fail in strict mode
    const event = {
      type: 'chunk',
      data: {
        logicalModelId: 'openai/gpt-4',  // camelCase — wrong
        actual_model_id: 'openai/gpt-4',
        round: 1,
        content: 'hello',
        done: false,
        seq: 2,
      },
    };
    expect(() => chunkEventSchema.parse(event)).toThrow();
  });
});

describe('CLI-E01 model_done event', () => {
  it('parses valid model_done event', () => {
    const event = {
      type: 'model_done',
      data: {
        logical_model_id: 'm1',
        actual_model_id: 'm1',
        round: 1,
        tokens: { input: 100, output: 200 },
        seq: 3,
      },
    };
    expect(() => modelDoneEventSchema.parse(event)).not.toThrow();
  });
});

describe('CLI-E01 model_error event', () => {
  it('parses valid model_error event with all required fields', () => {
    const event = {
      type: 'model_error',
      data: {
        logical_model_id: 'm1',
        actual_model_id: null,
        round: 1,
        error_type: 'timeout',
        action: 'skipped',
        degraded_to: null,
        message: 'timed out',
        seq: 4,
      },
    };
    expect(() => modelErrorEventSchema.parse(event)).not.toThrow();
  });

  it('rejects unknown action values', () => {
    const event = {
      type: 'model_error',
      data: {
        logical_model_id: 'm1',
        actual_model_id: null,
        round: 1,
        error_type: 'timeout',
        action: 'unknown_action',  // not allowed
        degraded_to: null,
        message: 'timed out',
        seq: 4,
      },
    };
    expect(() => modelErrorEventSchema.parse(event)).toThrow();
  });
});

describe('CLI-E01 round_done event', () => {
  it('parses valid round_done event', () => {
    const event = {
      type: 'round_done',
      data: {
        round: 1,
        completed_models: ['m1'],
        skipped_models: ['m2'],
        failed_models: [
          {
            logical_model_id: 'm2',
            actual_model_id: null,
            error_type: 'timeout',
            action: 'skipped',
          },
        ],
        total_models: 2,
        seq: 5,
      },
    };
    expect(() => roundDoneEventSchema.parse(event)).not.toThrow();
  });
});

describe('CLI-E01 anonymize event', () => {
  it('parses valid anonymize event', () => {
    const event = {
      type: 'anonymize',
      data: { round: 2, labels: ['Model A', 'Model B', 'Model C'], seq: 7 },
    };
    expect(() => anonymizeEventSchema.parse(event)).not.toThrow();
  });
});

describe('CLI-E01 round_summary event', () => {
  it('parses valid round_summary event', () => {
    const event = {
      type: 'round_summary',
      data: {
        round: 1,
        next_round: 2,
        ...SUMMARY_FIXTURE,
        seq: 6,
      },
    };
    expect(() => roundSummaryEventSchema.parse(event)).not.toThrow();
  });

  it('next_round can be null (after round 3)', () => {
    const event = {
      type: 'round_summary',
      data: { round: 3, next_round: null, ...SUMMARY_FIXTURE, seq: 6 },
    };
    expect(() => roundSummaryEventSchema.parse(event)).not.toThrow();
  });
});

describe('CLI-E01 summary event', () => {
  it('parses valid summary event', () => {
    const event = {
      type: 'summary',
      data: { ...SUMMARY_FIXTURE, seq: 8 },
    };
    expect(() => summaryEventSchema.parse(event)).not.toThrow();
  });

  it('requires disclaimer and is_degraded fields', () => {
    const event = {
      type: 'summary',
      data: {
        consensus: [],
        disagreements: [],
        recommendation: 'x',
        confidence: 'medium',
        open_questions: [],
        evidence_refs: [],
        // missing disclaimer and is_degraded
        seq: 1,
      },
    };
    expect(() => summaryEventSchema.parse(event)).toThrow();
  });
});

describe('CLI-E01 done event', () => {
  it('parses valid done event', () => {
    const event = {
      type: 'done',
      data: { total_raw_cost: 0.082, total_platform_price: 0.0995, seq: 9 },
    };
    expect(() => doneEventSchema.parse(event)).not.toThrow();
  });
});

describe('CLI-E01 restore event', () => {
  it('parses valid restore event', () => {
    const event = {
      type: 'restore',
      data: {
        resume_mode: 'state_restore',
        can_stream: false,
        current_status: 'completed',
        current_round: 3,
        last_completed_round: 4,
        completed_round_messages: [],
        summary: SUMMARY_FIXTURE,
      },
    };
    expect(() => restoreEventSchema.parse(event)).not.toThrow();
  });

  it('resume_mode must be state_restore', () => {
    const event = {
      type: 'restore',
      data: {
        resume_mode: 'live',  // wrong
        can_stream: true,
        current_status: 'streaming',
        current_round: 1,
        last_completed_round: 0,
        completed_round_messages: [],
        summary: null,
      },
    };
    expect(() => restoreEventSchema.parse(event)).toThrow();
  });
});

describe('CLI-E01 error event', () => {
  it('parses valid error event', () => {
    const event = {
      type: 'error',
      data: { code: 'ORCHESTRATOR_ERROR', message: 'something failed' },
    };
    expect(() => errorEventSchema.parse(event)).not.toThrow();
  });
});

describe('CLI-E01 interrupt_ack event', () => {
  it('parses valid interrupt_ack event', () => {
    const event = {
      type: 'interrupt_ack',
      data: { status: 'acknowledged', message: 'Interrupt accepted.', seq: 10 },
    };
    expect(() => interruptAckEventSchema.parse(event)).not.toThrow();
  });
});

// ─── Full discriminated union ─────────────────────────────────────────────────

describe('CLI-E01 sseEventSchema union covers all 12 types', () => {
  const validEvents = [
    { type: 'progress', data: { round: 1, total_rounds: 3, phase: 'independent', seq: 1 } },
    {
      type: 'chunk',
      data: {
        logical_model_id: 'm1', actual_model_id: 'm1',
        round: 1, content: 'hi', done: false, seq: 2,
      },
    },
    {
      type: 'model_done',
      data: {
        logical_model_id: 'm1', actual_model_id: 'm1',
        round: 1, tokens: { input: 50, output: 100 }, seq: 3,
      },
    },
    {
      type: 'model_error',
      data: {
        logical_model_id: 'm1', actual_model_id: null, round: 1,
        error_type: 'timeout', action: 'skipped', degraded_to: null,
        message: 'timed out', seq: 4,
      },
    },
    {
      type: 'round_done',
      data: {
        round: 1, completed_models: ['m1'], skipped_models: [],
        failed_models: [], total_models: 1, seq: 5,
      },
    },
    {
      type: 'round_summary',
      data: { round: 1, next_round: 2, ...SUMMARY_FIXTURE, seq: 6 },
    },
    { type: 'anonymize', data: { round: 2, labels: ['A', 'B'], seq: 7 } },
    { type: 'summary', data: { ...SUMMARY_FIXTURE, seq: 8 } },
    { type: 'done', data: { total_raw_cost: 0.1, total_platform_price: 0.12, seq: 9 } },
    {
      type: 'restore',
      data: {
        resume_mode: 'state_restore', can_stream: false,
        current_status: 'completed', current_round: 3,
        last_completed_round: 4, completed_round_messages: [],
        summary: null,
      },
    },
    { type: 'error', data: { code: 'ERR', message: 'boom' } },
    { type: 'interrupt_ack', data: { status: 'acknowledged', message: 'ok', seq: 10 } },
  ];

  it.each(validEvents)('parses %s event via discriminated union', (event) => {
    expect(() => sseEventSchema.parse(event)).not.toThrow();
  });

  it('covers exactly 12 event types', () => {
    expect(validEvents).toHaveLength(12);
  });
});
