import { describe, expect, it } from 'vitest';

import type {
  ActorContext,
  AnonymizeEvent,
  BillingCost,
  ChunkEvent,
  ConversationStatus,
  CreateDiscussionRequest,
  CreateDiscussionResponse,
  CreditTransactionType,
  DiscussionSummaryFinal,
  DiscussionTransition,
  DoneEvent,
  ErrorEvent,
  InterruptAckEvent,
  ModelDoneEvent,
  ModelErrorEvent,
  ProgressEvent,
  RoundSummaryEvent,
  RestoreEvent,
  RoundDoneEvent,
  RoundNumber,
  RoundType,
  SSEEvent,
  SSEEventType,
  SecretaryRawOutput,
  SummaryEvent,
  TerminalStatus,
} from '@/lib/types';

describe('type definitions compile-time checks', () => {
  it('ActorContext accepts all valid sources', () => {
    const cli: ActorContext = { userId: 'u1', source: 'cli' };
    const web: ActorContext = { userId: 'u2', source: 'web' };
    const test: ActorContext = { userId: 'u3', source: 'test' };
    expect(cli.source).toBe('cli');
    expect(web.source).toBe('web');
    expect(test.source).toBe('test');
  });

  it('ConversationStatus covers exactly 6 values', () => {
    const statuses: ConversationStatus[] = [
      'created',
      'streaming',
      'summarizing',
      'completed',
      'failed',
      'aborted',
    ];
    expect(statuses).toHaveLength(6);
  });

  it('TerminalStatus is subset of ConversationStatus', () => {
    const terminals: TerminalStatus[] = ['completed', 'failed', 'aborted'];
    expect(terminals).toHaveLength(3);
  });

  it('RoundType covers 3 values', () => {
    const types: RoundType[] = ['independent', 'review', 'rebuttal'];
    expect(types).toHaveLength(3);
  });

  it('RoundNumber covers 1/2/3', () => {
    const rounds: RoundNumber[] = [1, 2, 3];
    expect(rounds).toHaveLength(3);
  });

  it('DiscussionTransition covers all 9 whitelist transitions', () => {
    const transitions: DiscussionTransition[] = [
      { from: 'created', to: 'streaming' },
      { from: 'created', to: 'aborted' },
      { from: 'created', to: 'failed' },
      { from: 'streaming', to: 'streaming' },
      { from: 'streaming', to: 'summarizing' },
      { from: 'streaming', to: 'failed' },
      { from: 'streaming', to: 'aborted' },
      { from: 'summarizing', to: 'completed' },
      { from: 'summarizing', to: 'failed' },
    ];
    expect(transitions).toHaveLength(9);
  });

  it('SSEEventType covers exactly 12 event types', () => {
    const types: SSEEventType[] = [
      'progress',
      'chunk',
      'model_done',
      'model_error',
      'round_done',
      'round_summary',
      'anonymize',
      'summary',
      'done',
      'restore',
      'error',
      'interrupt_ack',
    ];
    expect(types).toHaveLength(12);
  });

  it('SSEEvent discriminated union works with type narrowing', () => {
    const event: SSEEvent = {
      type: 'chunk',
      data: {
        logical_model_id: 'claude',
        actual_model_id: 'claude',
        round: 1,
        content: 'hello',
        done: false,
        seq: 1,
      },
    };

    if (event.type === 'chunk') {
      expect(event.data.content).toBe('hello');
    }
  });

  it('all 12 SSEEvent variants can be constructed', () => {
    const summary: DiscussionSummaryFinal = {
      consensus: [
        {
          content: 'Proceed with a limited beta launch.',
          supporting_models: ['m1', 'm2'],
          evidence_refs: ['round-1'],
        },
      ],
      disagreements: [],
      recommendation: 'Proceed with a limited beta rollout.',
      confidence: 'medium',
      open_questions: [],
      evidence_refs: ['round-1'],
      disclaimer: 'Generated by secretary.',
      is_degraded: false,
    };

    const events: SSEEvent[] = [
      {
        type: 'progress',
        data: { round: 1, total_rounds: 3, phase: 'independent', seq: 1 },
      } satisfies ProgressEvent,
      {
        type: 'chunk',
        data: {
          logical_model_id: 'm1',
          actual_model_id: 'm1',
          round: 1,
          content: 'hi',
          done: false,
          seq: 2,
        },
      } satisfies ChunkEvent,
      {
        type: 'model_done',
        data: {
          logical_model_id: 'm1',
          actual_model_id: 'm1',
          round: 1,
          tokens: { input: 50, output: 150 },
          seq: 3,
        },
      } satisfies ModelDoneEvent,
      {
        type: 'model_error',
        data: {
          logical_model_id: 'm1',
          actual_model_id: null,
          round: 1,
          error_type: 'timeout',
          action: 'skipped',
          degraded_to: null,
          message: 'timed out',
          seq: 4,
        },
      } satisfies ModelErrorEvent,
      {
        type: 'round_done',
        data: {
          round: 1,
          completed_models: ['m1'],
          skipped_models: [],
          failed_models: [],
          total_models: 1,
          seq: 5,
        },
      } satisfies RoundDoneEvent,
      {
        type: 'round_summary',
        data: { round: 1, next_round: 2, ...summary, seq: 6 },
      } satisfies RoundSummaryEvent,
      {
        type: 'anonymize',
        data: { round: 2, labels: ['Model A', 'Model B'], seq: 7 },
      } satisfies AnonymizeEvent,
      { type: 'summary', data: { ...summary, seq: 8 } } satisfies SummaryEvent,
      {
        type: 'done',
        data: { total_raw_cost: 0.08, total_platform_price: 0.1, seq: 9 },
      } satisfies DoneEvent,
      {
        type: 'restore',
        data: {
          resume_mode: 'state_restore',
          can_stream: false,
          current_status: 'completed',
          current_round: 3,
          last_completed_round: 4,
          completed_round_messages: [],
          summary,
        },
      } satisfies RestoreEvent,
      { type: 'error', data: { code: 'ERR', message: 'boom' } } satisfies ErrorEvent,
      {
        type: 'interrupt_ack',
        data: { status: 'acknowledged', message: 'accepted', seq: 10 },
      } satisfies InterruptAckEvent,
    ];

    expect(events).toHaveLength(12);
  });

  it('CreditTransactionType covers 7 values', () => {
    const types: CreditTransactionType[] = [
      'hold',
      'settle',
      'release',
      'refund',
      'grant',
      'purchase',
      'monthly_reset',
    ];
    expect(types).toHaveLength(7);
  });

  it('BillingCost has raw_cost and platform_price', () => {
    const cost: BillingCost = { raw_cost: 0.082, platform_price: 0.0995 };
    expect(cost.raw_cost).toBe(0.082);
    expect(cost.platform_price).toBe(0.0995);
  });

  it('SecretaryRawOutput has all required fields', () => {
    const output: SecretaryRawOutput = {
      consensus: [
        {
          content: 'Models agree on staged rollout.',
          supporting_models: ['m1'],
          evidence_refs: ['r1'],
        },
      ],
      disagreements: [],
      recommendation: 'Start with a staged beta rollout.',
      confidence: 'medium',
      open_questions: ['How much support staffing is needed?'],
      evidence_refs: ['r1'],
    };
    expect(output.confidence).toBe('medium');
    expect(output.decision_boundary).toBeUndefined();
  });

  it('DiscussionSummaryFinal contains the final system fields', () => {
    const summary: DiscussionSummaryFinal = {
      consensus: [
        {
          content: 'Launch with a staged beta.',
          supporting_models: ['m1'],
          evidence_refs: ['r1'],
        },
      ],
      disagreements: [],
      recommendation: 'Launch with a staged beta rollout.',
      confidence: 'high',
      open_questions: [],
      evidence_refs: ['r1'],
      disclaimer: 'Generated by secretary.',
      is_degraded: false,
    };
    expect(summary.is_degraded).toBe(false);
  });

  it('CreateDiscussionRequest / Response types are correct', () => {
    const req: CreateDiscussionRequest = {
      topic: 'test topic',
      models: ['claude', 'gpt-4o'],
      mode: 'consensus',
      max_rounds: 3,
      idempotency_key: 'idem-1',
    };
    const res: CreateDiscussionResponse = {
      id: 'd1',
      status: 'created',
      estimated_raw_cost: 0.12,
      held_platform_amount: 0.15,
      stream_url: '/api/discussions/d1/stream',
    };
    expect(req.models).toHaveLength(2);
    expect(res.status).toBe('created');
  });
});
