import { describe, expect, it } from 'vitest';
import { z } from 'zod';

import type {
  ActorContext,
  CreateDiscussionRequest,
  CreateDiscussionResponse,
  DiscussionSummaryFinal,
  SSEEvent,
  SecretaryRawOutput,
} from '@/lib/types';
import {
  actorContextSchema,
  createDiscussionRequestSchema,
  createDiscussionResponseSchema,
  discussionStatusSchema,
  discussionSummaryFinalSchema,
  sseEventSchema,
  secretaryRawOutputSchema,
} from '@/lib/types/schemas';

describe('zod schemas', () => {
  it('parses ActorContext and rejects extra fields', () => {
    const parsed: ActorContext = actorContextSchema.parse({
      userId: 'user-1',
      source: 'cli',
    });

    expect(parsed.source).toBe('cli');
    expect(
      actorContextSchema.safeParse({
        userId: 'user-1',
        source: 'cli',
        extra: true,
      }).success
    ).toBe(false);
  });

  it('parses CreateDiscussionRequest and rejects invalid payloads', () => {
    const valid: CreateDiscussionRequest = createDiscussionRequestSchema.parse({
      topic: 'Which model should lead the synthesis?',
      models: ['claude', 'gpt-4o'],
      mode: 'consensus',
      max_rounds: 3,
      idempotency_key: 'idem-1',
    });

    expect(valid.models).toHaveLength(2);
    expect(
      createDiscussionRequestSchema.safeParse({
        topic: '',
        idempotency_key: 'idem-1',
      }).success
    ).toBe(false);
  });

  it('parses CreateDiscussionResponse with frozen status values', () => {
    const valid: CreateDiscussionResponse = createDiscussionResponseSchema.parse({
      id: 'discussion-1',
      status: 'created',
      estimated_raw_cost: 0.12,
      held_platform_amount: 0.15,
      stream_url: '/api/discussions/discussion-1/stream',
    });

    expect(valid.status).toBe('created');
    expect(discussionStatusSchema.safeParse('invalid').success).toBe(false);
  });

  it('parses Secretary output and final summary contract', () => {
    const rawOutput: SecretaryRawOutput = secretaryRawOutputSchema.parse({
      consensus: [
        {
          content: 'Models agree on a conservative rollout.',
          supporting_models: ['m1'],
          evidence_refs: ['ref-1'],
        },
      ],
      disagreements: [],
      recommendation: 'Start with an invite-only rollout.',
      confidence: 'medium',
      open_questions: ['How much monitoring is needed?'],
      evidence_refs: ['ref-1'],
    });

    const finalSummary: DiscussionSummaryFinal = discussionSummaryFinalSchema.parse({
      ...rawOutput,
      disclaimer: 'Generated by secretary.',
      is_degraded: false,
    });

    expect(finalSummary.confidence).toBe('medium');
    expect(
      secretaryRawOutputSchema.safeParse({
        ...rawOutput,
        confidence: 'certain',
      }).success
    ).toBe(false);
  });

  it('parses SSE events and rejects unknown event types / extra fields', () => {
    const event: SSEEvent = sseEventSchema.parse({
      type: 'chunk',
      data: {
        logical_model_id: 'claude',
        actual_model_id: 'claude',
        round: 1,
        content: 'streaming text',
        done: false,
        seq: 1,
      },
    });

    expect(event.type).toBe('chunk');
    expect(
      sseEventSchema.safeParse({
        type: 'chunk',
        data: {
          logical_model_id: 'claude',
          actual_model_id: 'claude',
          round: 1,
          content: 'streaming text',
          done: false,
          seq: 1,
          extra: true,
        },
      }).success
    ).toBe(false);
    expect(
      sseEventSchema.safeParse({
        type: 'unknown',
        data: {},
      }).success
    ).toBe(false);
  });

  it('parses all 11 SSE event types successfully', () => {
    const summary = {
      consensus: [
        {
          content: 'Proceed with a limited beta rollout.',
          supporting_models: ['m1'],
          evidence_refs: ['r1'],
        },
      ],
      disagreements: [],
      recommendation: 'Proceed with a limited beta rollout.',
      confidence: 'medium',
      open_questions: [],
      evidence_refs: ['r1'],
      disclaimer: 'Generated by secretary.',
      is_degraded: false,
    } as const;

    const samples = [
      { type: 'progress', data: { round: 1, total_rounds: 3, phase: 'starting', seq: 1 } },
      {
        type: 'chunk',
        data: {
          logical_model_id: 'm1',
          actual_model_id: 'm1',
          round: 1,
          content: 'hi',
          done: false,
          seq: 2,
        },
      },
      {
        type: 'model_done',
        data: {
          logical_model_id: 'm1',
          actual_model_id: 'm1',
          round: 1,
          tokens: { input: 100, output: 50 },
          seq: 3,
        },
      },
      {
        type: 'model_error',
        data: {
          logical_model_id: 'm1',
          actual_model_id: null,
          round: 1,
          error_type: 'timeout',
          action: 'skipped',
          degraded_to: null,
          message: 'timeout',
          seq: 4,
        },
      },
      {
        type: 'round_done',
        data: {
          round: 1,
          completed_models: ['m1'],
          skipped_models: [],
          failed_models: [],
          total_models: 1,
          seq: 5,
        },
      },
      { type: 'anonymize', data: { round: 2, labels: ['A', 'B'], seq: 6 } },
      { type: 'summary', data: { ...summary, seq: 7 } },
      { type: 'done', data: { total_raw_cost: 0.08, total_platform_price: 0.1, seq: 8 } },
      {
        type: 'restore',
        data: {
          resume_mode: 'state_restore',
          can_stream: false,
          current_status: 'completed',
          current_round: 3,
          last_completed_round: 3,
          completed_round_messages: [],
          summary,
        },
      },
      { type: 'error', data: { code: 'ERR', message: 'boom' } },
      {
        type: 'interrupt_ack',
        data: { status: 'acknowledged', message: 'accepted', seq: 9 },
      },
    ] as const;

    for (const sample of samples) {
      expect(() => sseEventSchema.parse(sample)).not.toThrow();
    }

    expect(samples).toHaveLength(11);
  });

  it('keeps z.infer results compatible with shared types', () => {
    const actorExample: z.infer<typeof actorContextSchema> = {
      userId: 'user-1',
      source: 'web',
    };
    const actorType: ActorContext = actorExample;
    expect(actorType.source).toBe('web');

    const requestExample: z.infer<typeof createDiscussionRequestSchema> = {
      topic: 'A topic',
      models: ['claude', 'gpt-4o'],
      idempotency_key: 'idem-1',
    };
    const requestType: CreateDiscussionRequest = requestExample;
    expect(requestType.models).toHaveLength(2);

    const eventExample: z.infer<typeof sseEventSchema> = {
      type: 'interrupt_ack',
      data: { status: 'acknowledged', message: 'accepted', seq: 1 },
    };
    const eventType: SSEEvent = eventExample;
    expect(eventType.type).toBe('interrupt_ack');
  });
});
